### ISSUE TITLE
Documentacion: Requisitos

### ISSUE THREAD

**Issue by psnti** [psnti/Jellyfish_Forecast#37]

**Comment by alvarag** [comment]
Adjunto memoria y anexos comentados.

[memoriaAAG.pdf](https://github.com/psnti/Jellyfish_Forecast/files/4468518/memoriaAAG.pdf)
[anexosAAG.pdf](https://github.com/psnti/Jellyfish_Forecast/files/4468520/anexosAAG.pdf)
