### ISSUE TITLE
Mejorar README de ambos repositorios

### ISSUE THREAD

**Issue by psnti** [psnti/Jellyfish_Forecast#96]

**Comment by alvarag** [comment]
Adjunto comentarios de memoria y anexos

[memoriaAAG.pdf](https://github.com/psnti/Jellyfish_Forecast/files/4836883/memoriaAAG.pdf)
[anexosAAG.pdf](https://github.com/psnti/Jellyfish_Forecast/files/4836885/anexosAAG.pdf)
